module.exports={
    GoogleClientID:"685829835524-vclh05h0ia7qrdkbiktkmbul05euueb6.apps.googleusercontent.com",
    GoogleClientSecret:"JBcMtz5QHWso09N5_dQeKCwF",
    COOKIEKEY:"afdsjfodgjhgjlhlvjhpi",
    SECRET_KEY:'@TeamIAF',
    ResetPassword:'@TeamBalticKnights',
    adminEmail:"naikaderohit833@gmail.com",
    API:"http://localhost:5001",
    EmailKey:"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",
    EMAIL_TO:"naikaderohit833@gmail.com",
    clientURL:"http://localhost:3001",
    EMAIL_FROM:"naikaderohit833@gmail.com"
}