const mongoose=require('mongoose');
const revenueSchema=new mongoose.Schema({
    name:{
        type:String,
        trim:true
    },
    email:{
        type:String,
        trim:true
    },
    number:{
        type:String,
        trim:true
    },
    date:{
        type:Date
    },
    UID:{
        type:Number
    },
    home_tax:{
        type:Number
    },
    light_tax:{
        type:Number
    },
    health_tax:{
        type:Number
    },
    water_tax:{
        type:Number
    },
    total:{
        type:Number
    },
    penalty_tax:{
        type:Number
    },
    warrant_tax:{
        type:Number
    },
    picture:{
        type:String,
        trim:true
    },
    filename:{
        type:String,
        trim:true
    },
    display:{
        type:Boolean,
        default:true
    }
},{
    timestamps:true
});

module.exports=mongoose.model('revenue',revenueSchema);